### ISSUE TITLE
POC for FirefoxAccounts as a Social login provider

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-iam#36]
**Stories**
- As a user, I want to be able to login to Mozilla properties using a Mozilla owner identity provider, such as Firefox Accounts.
- As a user, I want to benefit from Firefox Accounts improvements to my login experience, such as automatic browser login whenever supported, etc.

**Todo**
On DEV instances only:
- [x] Test webtask extension for custom social providers
- [x] Request staging or prod FxA token with scope'd permissions
- [x] Test webtask extension for FxA as a custom social provider
- [x] Test NLX with a FxA login button

This is a POC, not a production test. If the POC is successful, a production test will involve auth0 rules in order to verify MFA have been used and foxsec review of FxA + EIS approval.

**Comment by gdestuynder** [comment]
Requests filed on my behalf by FxA (for reference) https://github.com/mozilla/fxa-dev/pull/349 https://github.com/mozilla/fxa-oauth-server/issues/515

**Comment by gdestuynder** [comment]
**Docs**
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction#OAuth_2.0_API
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/OAuth_dashboard

**Comment by gdestuynder** [comment]
Well-known URL: https://accounts.firefox.com/.well-known/openid-configuration

**Comment by gdestuynder** [comment]
Sample (dummy, really) profile query for webtask:
```
function(accessToken, ctx, cb) {
  // call oauth2 APIwith the accesstoken and create the profile

  request.get('https://oauth-stable.dev.lcip.org/v1/profile', {
    'headers': {
      'Authorization': 'Bearer ' + access_token,
      'User-Agent': 'MozillaIAM-Auth0'
    }
  }, function(e, r, b) {
    if (e) return callback(e);
    if (r.statusCode !== 200) return callback(new Error('StatusCode:' + r.statusCode));
    callback(null, JSON.parse(b));
  });
  cb(null, profile);
}
```

This is to be enhanced with a profile mapper

**Comment by gdestuynder** [comment]
POC Completed.
NLX Login button support: https://github.com/gdestuynder/auth0-custom-lock/tree/fxa (cc @hidde )
Server-side fxa support: https://github.com/mozilla-iam/auth0-deploy/pull/171

Result of POC:
![image 1](https://user-images.githubusercontent.com/956866/36243463-77f65538-11d6-11e8-9ed3-f8b10e12e12d.png)

**Comment by gdestuynder** [comment]
here are logos for the official thing when this comes out of POC
https://github.com/mozilla/fxa/issues/283#issuecomment-367112362

**Comment by hmitsch** [comment]
FYI: Link to bugzilla for the [Firefox Accounts MFA/2FA implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1379677).

**Comment by gdestuynder** [comment]
Auth0 code for non-POC https://github.com/mozilla-iam/auth0-deploy/pull/183

**Comment by gdestuynder** [comment]
Dash error msg for 2fa enforcement https://github.com/mozilla-iam/sso-dashboard/pull/269

**Comment by gdestuynder** [comment]
Some enhancement to be done before release: https://github.com/mozilla-iam/auth0-deploy/issues/184
